# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rle <rle@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/28 09:03:31 by rle               #+#    #+#              #
#    Updated: 2017/04/12 16:09:04 by rle              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

OBJ = ft_memset.o \
	  ft_bzero.o \
	  ft_memcpy.o \
	  ft_memccpy.o \
	  ft_memmove.o \
	  ft_memchr.o \
	  ft_memcmp.o \
	  ft_strlen.o \
	  ft_strdup.o \
	  ft_strncpy.o \
	  ft_strcat.o \
	  ft_strncat.o \
	  ft_strlcat.o \
	  ft_strchr.o \
	  ft_strrchr.o \
	  ft_strstr.o \
	  ft_strnstr.o \
	  ft_strcmp.o \
	  ft_strncmp.o \
	  ft_atoi.o \
	  ft_isalpha.o \
	  ft_isdigit.o \
	  ft_isalnum.o \
	  ft_isascii.o \
	  ft_isprint.o \
	  ft_toupper.o \
	  ft_tolower.o \
	  ft_memalloc.o \
	  ft_memdel.o \
	  ft_strnew.o \
	  ft_strdel.o \
	  ft_strclr.o \
	  ft_striter.o \
	  ft_striteri.o \
	  ft_strmap.o \
	  ft_strmapi.o \
	  ft_strequ.o \
	  ft_strnequ.o \
	  ft_strsub.o \
	  ft_strjoin.o \
	  ft_strjoin.o \
	  ft_strtrim.o \
	  ft_strtrim.o \
	  ft_strsplit.o \
	  ft_itoa.o \
	  ft_putchar.o \
	  ft_putstr.o \
	  ft_putendl.o \
	  ft_putnbr.o \
	  ft_putchar_fd.o \
	  ft_putstr_fd.o \
	  ft_putendl_fd.o \
	  ft_putnbr_fd.o \
	  ft_strrev.o \
	  ft_lstnew.o \
	  ft_lstdelone.o \
	  ft_lstadd.o \
	  ft_lstdel.o \
	  ft_lstiter.o \
	  ft_lstmap.o \
	  ft_wd_len.o \
	  ft_count_wds.o \
	  ft_int_length.o \
	  ft_strn_append.o \
	  ft_copystr.o \
	  ft_realloc.o \
	  get_next_line.o

CC = gcc -Wall -Werror -Wextra -I ./includes

all: $(NAME)

$(NAME): $(OBJ)
	ar rc $(NAME) $(OBJ) 

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

bin: re
	make clean
